#ifndef COUNTRY_ROADS_HARDWARE_LOCATIONS_H_
#define COUNTRY_ROADS_HARDWARE_LOCATIONS_H_

#define RELAY_1 101
#define RELAY_2 102
#define RELAY_3 103
#define HTTP_REQUESTER 201

#endif //COUNTRY_ROADS_HARDWARE_LOCATIONS_H_
